version: 2.1
jobs:
  build:
    working_directory: ~/releases
    docker: # run the steps with Docker
      - image: circleci/node:10-browsers
    filters:
      # Both of the following conditions must be included!
      # Ignore any commit on any branch by default.
      # branches:
      #   only: master
      # Only act on version tags.
      # tags:
      #   only: /v[0-9]+(\.[0-9]+)*(\-rc(\.[0-9]+)?)?/

    steps:
      - checkout
    
      - add_ssh_keys:
          fingerprints:
            - "0f:13:87:d5:44:fc:86:9d:f8:ab:63:20:73:eb:d2:09"
      - run:
          name: Setup local environment
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm" >> $BASH_ENV
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            source $BASH_ENV
            nvm install node --lts
            git config --global user.email "turnrye@users.noreply.github.com"
            git config --global user.name "turnrye Deployment Script"
            curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run the new release
          command: |
            mkdir -p ./react-native/.git
            git clone --mirror https://github.com/facebook/react-native.git react-native/.git
            cd react-native
            git config --bool core.bare false
            git checkout master
            cd ..
            ./changelog-generator.js